# Generated by Django 5.1.5 on 2025-03-19 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuit', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, message='Deben ser 11 caracteres'), django.core.validators.MaxLengthValidator(11, message='Deben ser 11 caracteres')])),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
