# Generated by Django 5.1.5 on 2025-02-22 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('superficie', models.FloatField()),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campos', to='establecimiento.campo')),
            ],
        ),
    ]
