# Generated by Django 5.1.5 on 2025-03-17 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0002_alter_insumo_categoria_alter_insumo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('ciclo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='insumos.insumo')),
            ],
        ),
    ]
