# Generated by Django 5.1.5 on 2025-03-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='cantidad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='compra',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
