# Generated by Django 5.1.5 on 2025-03-17 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
        ('proveedor', '0002_alter_proveedor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='insumos.categoria'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='proveedor.proveedor'),
        ),
    ]
