# Generated by Django 5.1.5 on 2025-05-27 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('establecimiento', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='insumos.insumo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='establecimiento.lote')),
            ],
        ),
    ]
