# Generated by Django 5.1.5 on 2025-05-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes', '0001_initial'),
        ('establecimiento', '0001_initial'),
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='lote',
        ),
        migrations.CreateModel(
            name='OrdenesDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_detalle', to='insumos.insumo')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_detalle', to='Ordenes.ordenes')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenesLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_lote', to='establecimiento.lote')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_lote', to='Ordenes.ordenes')),
            ],
        ),
    ]
